### ISSUE TITLE
Octaves odd fingerings

### ISSUE THREAD

**Issue by lauralex** [marcomusy/pianoplayer#11]
Pianoplayer suggests 5-4 left hand fingering for an octave.

![output](https://user-images.githubusercontent.com/5181524/58372871-c3adac80-7f24-11e9-8bf0-4100ec473cc9.png)

**Comment by marcomusy** [comment]
@lauralex 
this should now be fixed in this latest release
![Screenshot from 2019-08-23 18-25-05](https://user-images.githubusercontent.com/32848391/63612799-671f6380-c5df-11e9-8e52-04c98329d481.png)
