### ISSUE TITLE
Can't open your app via Windows and Ubuntu

### ISSUE THREAD

**Issue by bukowiak** [marcomusy/pianoplayer#15]
`/usr/bin/python3: can't find '__main__' module in 'pianoplayer'`

**Comment by marcomusy** [comment]
I cannot reproduce the problem.
with google I found this which seems relevant:
https://stackoverflow.com/questions/42681801/python-cant-find-main-module/42681826

try to comment out the last if block in `pianoplayer/vtk_keyboard.py`:
```bash
git clone
cd pianoplayer/pianoplayer
edit vtk_keyboard.py
...
cd ..
pip install .
pianoplayer
```
