### ISSUE TITLE
consult

### ISSUE THREAD

**Issue by Wud1** [marcomusy/pianoplayer#16]
Hello, I also encountered a project about fingering. How can I run my data to your model?

**Comment by marcomusy** [comment]
Hi @Wud1 
what do you mean exactly by model? what format is it?

**Comment by Wud1** [comment]
> 您好，我还遇到了一个有关指法的项目。如何将数据运用于您的模型？



> 嗨@ Wud1
> ，您所说的确切是什么意思？它是什么格式？

@marcomusy 
I want to run my data with your code, my data is in Musicxml format.

**Comment by marcomusy** [comment]
sorry i cannot read chinese :)
`pianoplayer`supports musicxml file format so you should not have problems using it.

**Comment by Wud1** [comment]
Thank you very much. I've solved the problem.
