### ISSUE TITLE
Exception in Tkinter Callback

### ISSUE THREAD

**Issue by mathiasjg** [marcomusy/pianoplayer#19]
Love this program as it's very helpful in learning fingering for new songs but getting an Exception in Tkinter calklback on a couple scores and hoping you might be able to help?

```
Saving score to output.xml
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Matth\anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Matth\anaconda3\Scripts\pianoplayer", line 93, in generateCMD
    sf.write('xml', fp='output.xml')
  File "C:\Users\Matth\anaconda3\lib\site-packages\music21\stream\__init__.py", line 252, in write
    return super().write(*args, **kwargs)
  File "C:\Users\Matth\anaconda3\lib\site-packages\music21\base.py", line 2562, in write
    return formatWriter.write(self, regularizedConverterFormat, fp, subformats, **keywords)
  File "C:\Users\Matth\anaconda3\lib\site-packages\music21\converter\subConverters.py", line 927, in write
    dataBytes = generalExporter.parse()
  File "C:\Users\Matth\anaconda3\lib\site-packages\music21\musicxml\m21ToXml.py", line 363, in parse
    outObj = self.fromGeneralObject(obj)
  File "C:\Users\Matth\anaconda3\lib\site-packages\music21\musicxml\m21ToXml.py", line 399, in fromGeneralObject
    outObj = meth(obj)
  File "C:\Users\Matth\anaconda3\lib\site-packages\music21\musicxml\m21ToXml.py", line 411, in fromScore
    scOut = sc.makeNotation(inPlace=False)
  File "C:\Users\Matth\anaconda3\lib\site-packages\music21\stream\__init__.py", line 13127, in makeNotation
    **subroutineKeywords)
  File "C:\Users\Matth\anaconda3\lib\site-packages\music21\stream\__init__.py", line 6040, in makeNotation
    bestClef=bestClef)
  File "C:\Users\Matth\anaconda3\lib\site-packages\music21\stream\__init__.py", line 5765, in makeMeasures
    inPlace=inPlace,
  File "C:\Users\Matth\anaconda3\lib\site-packages\music21\stream\makeNotation.py", line 577, in makeMeasures
    'within any measures' % (e, start, end))
music21.exceptions21.StreamException: cannot place element Piano with start/end 180.0/180.0 within any measures
```

On a different score I get the following error:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Matth\anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Matth\anaconda3\Scripts\pianoplayer", line 89, in generateCMD
    self.lh.noteseq = reader(sf, beam=self.LeftHandBeam)
  File "C:\Users\Matth\anaconda3\lib\site-packages\pianoplayer\scorereader.py", line 32, in reader
    strm = sf.parts[beam].flat
  File "C:\Users\Matth\anaconda3\lib\site-packages\music21\stream\iterator.py", line 328, in __getitem__
    e = fe[k]
IndexError: list index out of range
```

I did some research and found the following:
`This error occurs when you run a program using the Canvas library (used from Unit 2 onwards) more than once. This is a known problem with Canvas, and is not caused by your programming. The only solution is to close all Python windows then re-run IDLE after each time you run your program.
`

Not sure if the above is relevant. Any idea on how to fix the issue?

**Comment by marcomusy** [comment]
Thanks for reporting this, to be honest i'm very familiar with neither windows nor Tkinter.
What happens if you run from command line `python pianoplayer score.xml` ?
About the second error message it's maybe because you need to specify the beam number with `-rbeam`, if not you maybe can post the score that causes the trouble.

**Comment by conde2** [comment]
@marcomusy I'm facing similar problem

<pre>meas.87   finger:1 on F3 
meas.87   finger:5 on E2 
meas.87   finger:0 on E3 
Saving score to output.xml
Exception in Tkinter callback
Traceback (most recent call last):
  File &quot;/usr/lib/python2.7/lib-tk/Tkinter.py&quot;, line 1547, in __call__
    return self.func(*args)
  File &quot;pianoplayer&quot;, line 93, in generateCMD
    sf.write(&apos;xml&apos;, fp=&apos;output.xml&apos;)
  File &quot;/home/joao/.local/lib/python2.7/site-packages/music21/stream/__init__.py&quot;, line 250, in write
    return super(Stream, self).write(*args, **kwargs)
  File &quot;/home/joao/.local/lib/python2.7/site-packages/music21/base.py&quot;, line 2555, in write
    return formatWriter.write(self, regularizedConverterFormat, fp, subformats, **keywords)
  File &quot;/home/joao/.local/lib/python2.7/site-packages/music21/converter/subConverters.py&quot;, line 864, in write
    dataBytes = generalExporter.parse()
  File &quot;/home/joao/.local/lib/python2.7/site-packages/music21/musicxml/m21ToXml.py&quot;, line 332, in parse
    return self.parseWellformedObject(outObj)
  File &quot;/home/joao/.local/lib/python2.7/site-packages/music21/musicxml/m21ToXml.py&quot;, line 340, in parseWellformedObject
    scoreExporter.parse()
  File &quot;/home/joao/.local/lib/python2.7/site-packages/music21/musicxml/m21ToXml.py&quot;, line 1222, in parse
    self.parsePartlikeScore()
  File &quot;/home/joao/.local/lib/python2.7/site-packages/music21/musicxml/m21ToXml.py&quot;, line 1402, in parsePartlikeScore
    pp.parse()
  File &quot;/home/joao/.local/lib/python2.7/site-packages/music21/musicxml/m21ToXml.py&quot;, line 2062, in parse
    mxMeasure = measureExporter.parse()
  File &quot;/home/joao/.local/lib/python2.7/site-packages/music21/musicxml/m21ToXml.py&quot;, line 2385, in parse
    self.mainElementsParse()
  File &quot;/home/joao/.local/lib/python2.7/site-packages/music21/musicxml/m21ToXml.py&quot;, line 2407, in mainElementsParse
    self.parseFlatElements(nonVoiceMeasureItems)
  File &quot;/home/joao/.local/lib/python2.7/site-packages/music21/musicxml/m21ToXml.py&quot;, line 2445, in parseFlatElements
    self.parseOneElement(n)
  File &quot;/home/joao/.local/lib/python2.7/site-packages/music21/musicxml/m21ToXml.py&quot;, line 2495, in parseOneElement
    meth(o)
  File &quot;/home/joao/.local/lib/python2.7/site-packages/music21/musicxml/m21ToXml.py&quot;, line 3043, in noteToXml
    mxLyric = self.lyricToXml(lyricObj)
  File &quot;/home/joao/.local/lib/python2.7/site-packages/music21/musicxml/m21ToXml.py&quot;, line 4613, in lyricToXml
    _setTagTextFromAttribute(l, mxLyric, &apos;text&apos;, forceEmpty=True)
  File &quot;/home/joao/.local/lib/python2.7/site-packages/music21/musicxml/m21ToXml.py&quot;, line 193, in _setTagTextFromAttribute
    subElement.text = str(value)
UnicodeEncodeError: &apos;ascii&apos; codec can&apos;t encode character u&apos;\xfa&apos; in position 2: ordinal not in range(128)
</pre>

**Comment by marcomusy** [comment]
Should be fixed in the latest release.
