### ISSUE TITLE
Double sharps are not recognized

### ISSUE THREAD

**Issue by AmitMY** [marcomusy/pianoplayer#21]
So for this score:
https://musescore.com/user/147231/scores/1029831

I get many errors:
> ERROR note not found F##

Definitely makes sense why it's not recognized, just wanted to let you know in case you want to fix

**Comment by Cool-Joe** [comment]
Edit utils.py, def keypos(n) and add these lines:
    elif n.name == 'C##': step = k *1.5
    elif n.name == 'D##': step = k *2.5
    elif n.name == 'F##': step = k *4.5
    elif n.name == 'G##': step = k *5.5

**Comment by marcomusy** [comment]
Fixed in the latest release.
