### ISSUE TITLE
" Using cached vtkplotter-2020.3.1.tar.gz (18.4 MB) ERROR: Could not find a version that satisfies the requirement vtk (from vtkplotter->pianoplayer) (from versions: none) ERROR: No matching distribution found for vtk (from vtkplotter->pianoplayer)"

### ISSUE THREAD

**Issue by gabezilla52** [marcomusy/pianoplayer#25]
Hi, I'm trying to install this for windows 10 and I get this error when I enter "pip install --upgrade pianoplayer" what should I do? I'm using python 3.8.5 if that matters.

**Comment by marcomusy** [comment]
uhm try first
`pip install vtk==8.1.2`

**Comment by gabezilla52** [comment]
same error

**Comment by gabezilla52** [comment]
> same error
Not exactly the same but basically 
"ERROR: Could not find a version that satisfies the requirement vtk==8.1.2 (from versions: none)
ERROR: No matching distribution found for vtk==8.1.2"

**Comment by marcomusy** [comment]
very strange, it seems a `pip` problem, unrelated to `pianoplayer`.

you can try to ignore vtk with
`pip install music21`
`pip install --no-deps pianoplayer`

**Comment by gabezilla52** [comment]
Ignoring the vtk worked! Thanks! Now that I have it running, how do I save output.xml as it's own file?

**Comment by gabezilla52** [comment]
Ignoring the vtk worked! Thanks for your help!.

**Comment by marcomusy** [comment]
You're welcome :)
