### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by BrendRR** [marcomusy/pianoplayer#26]
Hello!
The last month, i've been trying to install this program, but i just can't seem to do it.
I never worked with python before, but i managed to get pip install working now.
When i put in the pip install --upgrade pianoplayer , it says :

Collecting pianoplayer
  Using cached pianoplayer-2.1.0.tar.gz (1.2 MB)
Collecting music21
  Using cached music21-5.7.2.tar.gz (18.5 MB)
Collecting vtkplotter
  Using cached vtkplotter-2020.3.1.tar.gz (18.4 MB)
ERROR: Could not find a version that satisfies the requirement vtk (from vtkplotter->pianoplayer) (from versions: none)
ERROR: No matching distribution found for vtk (from vtkplotter->pianoplayer)

when i then try to open the batch file, it just flashes and dissapears.
Could someone please help me out?
Thank you!
Regards,
Brend

**Comment by BrendRR** [comment]
Hello, 
After a lot of trying out various things, i got it to work!
A massive thanks!
I did ended up using anaconda.
I'm wondering, why are there so few programs like this, is it so hard to write, or do most pianists prefer to write their own fingering?

**Comment by marcomusy** [comment]
Great :) 

> why are there so few programs like this, is it so hard to write, or do most pianists prefer to write their own fingering?

I think it's a combination of various factors.. it's not easy to write it, there are many possible approaches, the results are generally poor when judged by experienced pianists (`pianoplayer` does indeed produce some nonsense fingering in a few places...).
Pianists vary a lot in fingering choices for the same piece too!

So I hope you'll find the program useful or at least informative beyond all these caveats!

I tried installing the program on an old windows machine and managed to do it without anaconda, so i'll post the recipe in a separate issue.
