### ISSUE TITLE
AttributeError: 'Instrument' object has no attribute 'tie'

### ISSUE THREAD

**Issue by Who-Plays** [marcomusy/pianoplayer#29]
I'm getting the following error when running `pianoplayer "xy.mid" --verbose -n10 -rvz`
 (tested on Windows with Python 3.8 & 3.7, and on Manjaro python 3.8)
```
Traceback (most recent call last):
  File "/home/anton/.local/bin/pianoplayer", line 195, in <module>
    rh.noteseq = reader(sf, beam=args.rbeam)
  File "/home/anton/.local/lib/python3.8/site-packages/pianoplayer/scorereader.py", line 51, in reader
    if n.tie and (n.tie.type=='continue' or n.tie.type=='stop'): continue
AttributeError: 'Instrument' object has no attribute 'tie'
```

**Comment by marcomusy** [comment]
The error is coming from `music21`, what version is it?

**Comment by fchazel** [comment]
I had the same issue with version ```6.3.0``` of ```music21```. 
I downgraded to version ```6.1.0``` and the error went away

To downgrade:
```pip install --upgrade music21==6.1.0```

**Comment by marcomusy** [comment]
Thanks @fchazel !
I need to check what has changed in `music21` or specify the version to import in requirements..

**Comment by marcomusy** [comment]
Error should be fixed in the latest release.
