### ISSUE TITLE
Odd results for some accidentals

### ISSUE THREAD

**Issue by jncarey** [marcomusy/pianoplayer#3]
This is a neat piece of software -- thanks for writing it!

I've been playing with it a bit and noticed that for some "weird" accidentals like Cb the program outputs bizarre fingering choices. If I rewrite the note as B the fingering makes much more sense. I haven't tried the other comparable accidentals (B#, E#, Fb) to know if this is a general or specific problem (nor have I looked at double sharps or double flats). You may not even be actively working on this software anymore, but in case you are this is a minor issue that could use correcting. Thanks!

Best,
Jeffrey

**Comment by mhoangvslev** [comment]
I think that fingering is completely per person basis. It is interesting to see a methodical approach to unify figering techniques, but I think ultimately, you should always bring a pencil with you :)

**Comment by marcomusy** [comment]
Dear Jeffrey, thanks for your comment which for some reason I didn't notice.
I'm currently revising this package so I will try to reproduce and fix the bug you mentioned!
