### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by mhoangvslev** [marcomusy/pianoplayer#4]
I ran this command on Windows
python setup.py install

How can I launch the program?

**Comment by marcomusy** [comment]
Hi 
I just committed a new version.
You can just use 
(sudo) pip install pianoplayer
and run it with
pianoplayer file.xml

**Comment by mhoangvslev** [comment]
Thank you, I wonder if there is a windows-friendly approach to use it?

**Comment by marcomusy** [comment]
I never used windows. :-)
I guess the friendliest would be using anaconda (?)

**Comment by mhoangvslev** [comment]
I think you should keep the previous commit as a separated branch for Windows users

**Comment by marcomusy** [comment]
doesn't the latest one work with windows?

**Comment by mhoangvslev** [comment]
the binary only works on linux system

**Comment by mhoangvslev** [comment]
@marcomusy When I run the binary under console, Windows prompts me to choose a program to execute.

**Comment by marcomusy** [comment]
if with binary you refer to the 'pianoplayer' file, then this is not a binary but a python script without the .py extension (see e.g. https://docs.python.org/3.3/using/windows.html#shebang-lines )
What if you try 
python pianoplayer
or
py pianoplayer ?

**Comment by mhoangvslev** [comment]
Pardon my Python skills :)
