### ISSUE TITLE
Hand size keeps defaulting to M, MuseScore3 not showing fingering

### ISSUE THREAD

**Issue by kchurch05** [marcomusy/pianoplayer#43]
Running this on Windows, so not sure how much of it has to do with this!

Whenever I try to run it from either the GUI or command line using -S, -XS, etc, it defaults to M. It also seems to run through it twice (e.g., I see _'Your hand span set to size-M which is 17.22 cm
(max relaxed distance between thumb and pinkie)'_ appear twice with the fingering output following it.

Additionally, opening the output.xml file in MuseScore3 does not show any fingering, just the music. Scanning through the output file XML doesn't seem to clearly show any fingering.

My apologies if this has already been addressed - I've searched through the issues and haven't seen anything in regard to these two issues!

**Comment by PRamoneda** [comment]
Are you using the pip version or the Github version? The Github version is in the beta stage. I would recommend you to use the pip ( 2.0. release )

**Comment by kchurch05** [comment]
I'm using the Github version, I believe. I'll try the pip version and report back. :)

**Comment by kchurch05** [comment]
Closing issue as reinstalling using pip has solved it. Thanks @PRamoneda !
