### ISSUE TITLE
Suggestion to UI

### ISSUE THREAD

**Issue by mhoangvslev** [marcomusy/pianoplayer#6]
Instead of writing fingering numbers as lyrics, could you consider using MuseScore's fingering notation? I think it would be more ergonomic and aesthetically more pleasing.

**Comment by hofst** [comment]
+1 that would be great!

**Comment by mhoangvslev** [comment]
send the author a pull request if you like.

**Comment by marcomusy** [comment]
@hofst 
following your code changes I tried shifting the numbers with adding  something like                  
                    # muf = Fingering(best_finger) # cannot shift them to make them visible
                    # sty = Style()
                    # sty.placement = 'below'
                    # sty.offset = .90
                    # sty.absoluteY = 30
                    # muf.style = sty
                    # an.note21.articulations.append(muf)

but there is no effect, so i'm switching back to the lyrics for the moment :(

**Comment by hofst** [comment]
@marcomusy 

I also quickly noticed that there are some issues left, I believe I now have solved them all:

- My patch for pianoplayer still had some problems with chords. Here is a working version:
https://github.com/hofst/pianoplayer/commits/master
- Also, the music21 library did not process articulations for fingers correctly, I patched it as well:
https://github.com/hofst/music21

I will file proper pull requests when I find time. With those two patches, you will be able to emit properly fingered musicxml files.

Lastly, musescore 2 does not align fingerings properly. musescore 3 (or other programs like sibelius) should work fine. If you use musescore 2, you can either use the plugin "fixfingering" (https://musescore.org/en/project/fingering-positioner). Alternatively, as I do, you can configure the musescore2 style->text->fingerings settings as follows:
- font size 6
- Horizontal spacing: 1.6sp
- Vertical spacing: 1.1sp

Demo:
![unbenannt](https://user-images.githubusercontent.com/2535762/44363003-1dc7a000-a4c3-11e8-9402-c2ef11078867.PNG)

**Comment by hofst** [comment]
Pleasure ;) I applied for a a pull request for music21. Without that patch the fingerings for chords won't work yet:
https://github.com/cuthbertLab/music21/pull/323

**Comment by hofst** [comment]
the pull request has been approved, so fingerings should now work with the next official version of music21:
https://github.com/cuthbertLab/music21/pull/323#pullrequestreview-148662787
